// app-react/src/App.js
import React from 'react';
import moment from 'moment';
import './App.css';

const targetTime = moment('2020-10-04T23:59:59')

class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      days: 0,
      hours: 0,
      minutes: 0,
      seconds: 0
    }
  }

  componentDidMount() {
    this.updateCountdown()
    setInterval(() => this.updateCountdown(), 1000)
  }

  updateCountdown() {
    const currTime = moment()
    const diffTime = moment.duration(targetTime.diff(currTime))

    this.setState({
      days: diffTime.days(),
      hours: diffTime.hours(),
      minutes: diffTime.minutes(),
      seconds: diffTime.seconds()
    })
  }

  render() {
    return (
      <div className="cont">
        <div className="countdown">
          <div>
            <span >{this.state.days}</span>
            <span>дена</span>
          </div>
          <div>
            <span>{this.state.hours}</span>
            <span>часа</span>
          </div>
          <div>
            <span>{this.state.minutes}</span>
            <span>минути</span>
          </div>
          <div>
            <span>{this.state.seconds}</span>
            <span>секунди</span>
          </div>
        </div>
      </div>
    )
  }
}

export default App;

// app-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import * as moment from 'moment';

const targetTime = moment('2020-10-04T23:59:59')

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app-angular';
  days = 0
  hours = 0
  minutes = 0
  seconds = 0

  ngOnInit() {
    this.updateCountdown()
    setInterval(() => this.updateCountdown(), 1000)
  }

  updateCountdown() {
    const currTime = moment()
    const diffTime = moment.duration(targetTime.diff(currTime))

    this.days = diffTime.days()
    this.hours = diffTime.hours()
    this.minutes = diffTime.minutes()
    this.seconds = diffTime.seconds()
  }
}

<div class="cont">
  <div class="countdown">
    <div>
      <span>{{days}}</span>
      <span>дена</span>
    </div>
    <div>
      <span>{{hours}}</span>
      <span>часа</span>
    </div>
    <div>
      <span>{{minutes}}</span>
      <span>минути</span>
    </div>
    <div>
      <span>{{seconds}}</span>
      <span>секунди</span>
    </div>
  </div>
</div>
